spring:
#  config:
#    activate:
#      on-profile: local
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demodb
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      data-locations: classpath:data.sql
      mode: always
